---
- name: Create the subdirectories for the symlinks
  block:
    - name: split the path
      set_fact:
        split_path: "{{ fullpath.split('/') }}"

    - name: get the base path of the file
      debug:
        msg: "{{ split_path[:-1] | join('/') }}"
